- id: check-powershell-scripts
  name: Check PowerShell Scripts
  description: This hook uses PSAnalyzer and checks PowerShell scripts files
  language: docker
  entry: pwsh_checker.ps1
  files: '.+\.ps1$'
