- id: check-powershell-scripts
  name: Check PowerShell Scripts
  description: This hook uses PSAnalyzer and checks PowerShell scripts files
  entry: python -m esp_pwsh_check
  language: python
  files: '.+\.ps1$'
